opt_in_rules:
- line_length

line_length:
  ignores_comments: true
  warning: 150

disabled_rules:
  - trailing_whitespace

identifier_name:
  min_length: 2

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - CathayTests
