osx_image: xcode11.2
language: swift
os: osx

xcode_project: Cathay.xcodeproj
xcode_scheme: Cathay
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11

cache:
  directories:
    - Carthage
    - ~/.danger-swift

before_install:
  - sh ./setup.sh
  - brew install danger/tap/danger-swift

script:
- xcodebuild test -scheme Cathay -derivedDataPath Build/ -enableCodeCoverage YES
- danger-swift ci pr https://github.com/duyquang91/Cathay/pulls/${TRAVIS_PULL_REQUEST}
