name: Notify

on: 
  commit_comment: 
  - 'feat: *'


jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
