name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: xcodebuild -version && sh ./setup.sh
    #- name: Build
    #  run: xcodebuild -sdk iphonesimulator -scheme Cathay -configuration Debug build
    - name: Run Unit Tests
      run: xcodebuild test -scheme CathayTests -destination 'platform=iOS Simulator,OS=13.2.2,name=iPhone 11'
