name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: sh ./setup.sh
    - name: Build
      run: xcodebuild -destination 'platform=iOS Simulator,OS=13.1,name=iPhone 11' -scheme Cathay -configuration Debug build
    - name: Run Unit Tests
      run: xcodebuild test -scheme CathayTests -destination 'platform=iOS Simulator,OS=13.2.2,name=iPhone 11'
