name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup
      run: sh ./setup.sh
    #- name: Build
    #  run: xcodebuild -sdk iphonesimulator -scheme Cathay -configuration Debug build
    - name: Run Unit Tests
      run: xcodebuild clean test -project Cathay.xcodeproj -scheme CathayTests -destination 'platform=iOS Simulator,OS=13.1,name=iPhone 11'
